[project]
name = "webtoon-download"
dynamic = ["version"]
description = "Download episodes from WEBTOON"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "aiopath>=0.7.7",
    "beautifulsoup4>=4.14.2",
    "yarl>=1.22.0",
]
